### ISSUE TITLE
add better questions to questions.txt

### ISSUE THREAD

**Issue by Arjun1372000** [Arjun1372000/beginner_data_project#1]
Hey!
If you could add or edit some questions in questions.txt to better suit the purpose i.e. to get a better understanding of pandas module, then please do so.
Note: I'm new to GitHub and still exploring about pull requests and all that, so it's fine if you could just reply to this.

**Comment by MatterAndy** [comment]
Hello. I added a few more questions in PR #4. Hope this helps!
